### ISSUE TITLE
Diagonal and Exponentials

### ISSUE THREAD

**Issue by goodhamgupta** [versilov/matrex#12]
Hi,
Thank you so much for this wonderful library!! Would it be possible to get the diagonal of a square matrix and apply exponential functions to it with the current implementation?

**Comment by versilov** [comment]
Hello!

I've added Matrex.diag() function to the `array` branch of the project, so now you can do:

```elixir
iex(2)> m = Matrex.random(5, 5)  
#Matrex[5×5]:float32
┌                                         ┐
│ 0.39985 0.60632 0.39448 0.26069 0.02509 │
│  0.6064  0.7455 0.74208 0.08564 0.36913 │
│ 0.41704 0.94884 0.12432 0.27186  0.8584 │
│ 0.26978 0.47607 0.22123 0.30906 0.81278 │
│    0.73     0.1   0.815 0.59703 0.52114 │
└                                         ┘
iex(3)> Matrex.diag(m)
#Matrex[5×1]:float32
┌         ┐
│ 0.39985 │
│  0.7455 │
│ 0.12432 │
│ 0.30906 │
│ 0.52114 │
└         ┘
iex(4)> Matrex.diag(m) |> Matrex.apply(:exp)
#Matrex[5×1]:float32
┌         ┐
│ 1.49161 │
│ 2.10749 │
│ 1.13238 │
│ 1.36214 │
│ 1.68394 │
└         ┘
```
Is this what you requested?

You will have to switch to not finished yet `array` branch to use it.

**Comment by goodhamgupta** [comment]
Thanks for your help @versilov! Apologies for the confusion caused with the `exponential` term. I'm currently trying to apply fractional powers to a matrix( A<sup>1/2</sup>, A<sup>1/n</sup>, etc.). Is there a way to apply these fractional powers to the matrices directly?

**Comment by goodhamgupta** [comment]
Nevermind, I figured I can use the `apply` function present in the branch `array` for my purpose. Thank you for your help and this awesome library @versilov! 😄

**Comment by versilov** [comment]
You are welcome!
Thank you for feedback, and `diag/1` function was actually missing from the library:)
