### ISSUE TITLE
delete boobs function

### ISSUE THREAD

**Issue by vothane** [versilov/matrex#20]
I suggest deleting the ___boobs___ function. Other then a vessel for joke delivery 
but this is nonsense.

```elixir
@doc """
Function of a surface with two hills.
"""
@spec boobs(float, float) :: float
def boobs(x, y) do
  x = (x - 40) / 4
  y = (y - 40) / 4

  :math.exp(-:math.pow(:math.pow(x - 4, 2) + :math.pow(y - 4, 2), 2) / 1000) +
    :math.exp(-:math.pow(:math.pow(x + 4, 2) + :math.pow(y + 4, 2), 2) / 1000) +
    0.1 * :math.exp(-:math.pow(:math.pow(x + 4, 2) + :math.pow(y + 4, 2), 2)) +
    0.1 * :math.exp(-:math.pow(:math.pow(x - 4, 2) + :math.pow(y - 4, 2), 2))
end
```

I like jokes probably more than the next person unless they offend or cause 
potential harm. Also I am just as guilty for this kind of thing, because we all
are idiots. MISTAKES MADE. LESSONS LEARN. WE GROW, IF GIVEN ROOM.

Formally and moreover:

> ... this form of code and practice may cause potential harm to ~~some~~ all  
> participants in OSS. In a larger overarching context, condones and perpetuates
> this insidious behavior in a larger community. Dudes, basically ...  

Not my intention to be self-righteous judge and high-horse executioner. But there 
going to be a large audience that'll be reading this (long and overly complex story). 
They may not be so lenient in thought and/or action. Bottom-line, better to save 
your ass. So to speak.

**Comment by versilov** [comment]
Sounds sane to me.

Function is used for testing purposes, so I don't want to remove it, unless you suggest some other surface-generating function(s) to replace it.

But I renamed it to `twin_peaks/2` for now.
