### ISSUE TITLE
Floating point issue for larger numbers

### ISSUE THREAD

**Issue by srih4ri** [versilov/matrex#27]
```elixir
iex(24)> Matrex.new([[4_000_022.6578]])
#Matrex[1×1]
┌           ┐
│4000022.75 │
└           ┘
```

Passing a fairly large number causes the number to be rounded off - this gives me wrong values when I perform operations on these matrices.

Is this a known limitation? Are there any work-arounds for this to work with larger numbers?

Thanks in advance.

/cc @goodhamgupta

**Comment by versilov** [comment]
This is a limitation of float32 type, which gives most accurate representation of your number as 4.00002275E6.
You can use matrices of doubles (float64), if you need more precision. They are available in the 'array' branch of matrex.

**Comment by vasuadari** [comment]
@versilov It would be nice to document this limitation.

**Comment by srih4ri** [comment]
I was not able to compile array branch in debian or alpine (tried different options for MATREX_BLAS too).

Compiling fails with same error as seen in travis CI  : https://travis-ci.org/github/versilov/matrex/builds/595219458

Not much familiar with C, so not sure what's breaking.FWIW, the compile works fine with Mac using Accelerate framework.
