### ISSUE TITLE
Benchmark against Numpy

### ISSUE THREAD

**Issue by john-eevee** [versilov/matrex#3]
Foremost, thanks for this amazing project!

I noticed that on the benchmark section on the readme there are only comparisons between Elixir/Erlang libraries, which are not that fast/used.

Would be possible to benchmark against Numpy ? So we get a perspective against the most used library on this domain and how well  we can expect matrex to perform?

**Comment by versilov** [comment]
Hi!

That's a great idea! Given I have almost zero experience with python this won't be that easy, though.
I think, we can start with existing numpy benchmarks and building some very similar setups with matrex.

**Comment by versilov** [comment]
@sleepiejohn, here are preliminary results, run on the same MacBook Pro 2015.
But I believe they are not very correct, because it looks like NumPy did not use BLAS.
Anyway, on initialization operations (zeros, ones & eye) we are surely ahead of NumPy.
Need python's AVS (airspeed velocity) specialist to verify results.

```
## MatrexBench (Elixir)
benchmark name       iterations   average time
time_zeros_100          1000000   1.55 µs/op  (1.5x slower)
time_ones_100           1000000   2.00 µs/op    (same)
time_eye_100             500000   3.08 µs/op      (1.8x faster)
time_eye_3000               500   2251.93 µs/op  (6.8x faster)
time_dot_d_dot_b_c        50000   65.08 µs/op (1.2x faster)
time_dot_trans_a_at       10000   142.30 µs/op (4x faster)
time_dot_trans_at_a       10000   261.85 µs/op (6x faster)
time_dot_a_b               5000   647.39 µs/op    (4x faster)

NumPy bench (Python)
[ 32.43%] ··· Running bench_core.Core.time_eye_100                      5.56μs
[ 35.14%] ··· Running bench_core.Core.time_eye_3000                    15.47ms
[ 45.95%] ··· Running bench_core.Core.time_ones_100                     2.18μs
[ 56.76%] ··· Running bench_core.Core.time_zeros_100                    951.36ns
[  5.00%] ··· Running bench_linalg.Eindot.time_dot_a_b                   2.42ms
[ 10.00%] ··· Running bench_linalg.Eindot.time_dot_d_dot_b_c          79.69μs
[ 15.00%] ··· Running bench_linalg.Eindot.time_dot_trans_a_at          606.27μs
[ 25.00%] ··· Running bench_linalg.Eindot.time_dot_trans_at_a          1.67ms
```

**Comment by john-eevee** [comment]
Interesting results. I read the benchmark documentation on numpy repo, seems that it just need to be run, everything else is configured already.

I did search for the BLAS implementation which numpy uses, you can  check running `python -c "import numpy; print(numpy.show_config());"` but the [SO awnser](https://stackoverflow.com/questions/37184618/find-out-if-which-blas-library-is-used-by-numpy) also states that it is not very accurate, the best is to use `ldd` on *nix OSes like:

`$ ldd $PYTHON_HOME/Lib/site-packages/numpy/core/multiarray.so`

**Comment by versilov** [comment]
Don't have an `ldd` on MacOS, and `otool -L` gave me this:
```
$ otool -L multiarray.cpython-36m-darwin.so
multiarray.cpython-36m-darwin.so:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
Looks like it uses Accelerate framework, but benchmark results are still hard to believe. How can we be that much faster?

I have logistic regression and one-layer NN examples on MNIST digits in Matrex, will try to find these built with NumPy and compare timings tomorrow.

**Comment by versilov** [comment]
Another benchmark shows Matrex is about 2 times faster, than NumPy in matrix dot product.
[This article](http://arogozhnikov.github.io/2015/01/06/benchmarks-of-speed-numpy-vs-all.html) tells us that NumPy itself is not the fastest beast in the Python world.

**Comment by john-eevee** [comment]
Yes you are using Accelerate, as am I using Intel MKL (Windows).

Numpy isn't the fastest implementation, but is the most used.

I was wondering to do a minst benchmark too! For a more "real case" bench. If I found something I will let you know!

**Comment by john-eevee** [comment]
Found [this](https://github.com/michelucci/Logistic-Regression-Explained) nice implementation, but seems it uses back propagation. Should give us an idea of how to implement only with numpy. Other alternative is to use scikit although it is a higher level of abstraction.

**Comment by chrismcg** [comment]
I translated the Ng course exercises to python using both plain numpy and scikit-learn as an exercise a while back so there might be something useful in here https://github.com/chrismcg/machine_learning_ng

**Comment by versilov** [comment]
@chrismcg that's great, because functions in `Matrex.Algorithms` module are also ported from my Ng course exercises, so, they should be very comparable!

**Comment by versilov** [comment]
@chrismcg, I've peeked into you code — you use some built-in optimizer via `op.minimize`,
while I optimize with `fmincg()`, ported from Octave to Elixir.
So the comparison would not be correct between those.

And Python's optimizer is several times faster, yes. Would be nice to have some of these in matrex too.

I plan to to fine tune numpy's built-in benchmarks — increase number of iterations, so that we could compare them to matrex honestly.

**Comment by chrismcg** [comment]
Ah yes, I was concentrating on the ML bits so just used the built in optimization code. I'd love if there were more optimization choices on the beam. It could be worth seeing if GSL & dirty threads would work.

**Comment by versilov** [comment]
Finally made the comparison. Matrex was so much faster than NumPy because NumPy uses 64-bit floats by default, while Matrex uses 32-bit floats.

After bringing element size to the same value they seem to be on par in performance: Matrex twice as fast on element-wise operations, while NumPy is 8% faster on dot product.
