### ISSUE TITLE
Benchmark against Graphmath

### ISSUE THREAD

**Issue by crertel** [versilov/matrex#5]
Awesome work!

Would you mind benching against my library? 

https://www.hex.pm/packages/graphmath

We have somewhat different use cases, but I'd be curious to see how pure elixir stands up for the things tested. Thank you!

**Comment by versilov** [comment]
Hi! 
Thank you.

Surely will do, I am curious also.

**Comment by versilov** [comment]
@crertel , here is the bench for matrix multiplication. 
GraphMath goes second to Matrex, but deviation from the average is huge.

Surely, if you use dedicated SIMD operations for 3 & 4 element vectors you can beat up everyone!

```
##### With input 3x3 #####
Name                ips        average  deviation         median         99th %
Matrex        3624.36 K        0.28 μs    ±35.11%        0.26 μs        0.51 μs
GraphMath     1310.16 K        0.76 μs   ±247.15%        0.70 μs        1.70 μs
Matrix         372.58 K        2.68 μs    ±47.31%        2.40 μs        6.20 μs
Numexy          89.72 K       11.15 μs   ±128.04%           9 μs          30 μs
ExMatrix        35.76 K       27.96 μs    ±47.28%          24 μs          67 μs

Comparison:
Matrex        3624.36 K
GraphMath     1310.16 K - 2.77x slower
Matrix         372.58 K - 9.73x slower
Numexy          89.72 K - 40.40x slower
ExMatrix        35.76 K - 101.35x slower
```

**Comment by crertel** [comment]
Woohoo!

Yeah, the next step in this was opaque blobs + SIMD.

I wish the BEAM folks actually acknowledged packed doubles/floats as a datatype :(
